development:
  adapter: postgresql
  encoding: unicode
  database: yelp_development
  pool: 5
  username: spike
  password: spsp1990

test:
  adapter: postgresql
  encoding: unicode
  database: yelp_test
  pool: 5
  username: spike
  password: spsp1990